### ISSUE TITLE
Do you have an idea how to handle wrapper Jar generated by system gradle installation

### ISSUE THREAD

**Issue by tegoo** [ZacSweers/check-gradle-checksums#1]
Hi. Nice helper script. May be you also know how to handle checksum verification in case of Gradle Wrapper JAR generated by distribution gradle installation.

See more details in my question here:
https://stackoverflow.com/questions/59375194/why-gradle-wrapper-jar-checksum-doesnt-match-when-generated-by-gradle-binary-fr

**Comment by ZacSweers** [comment]
I don't, please keep this issue tracker for issues with the project. Questions like this should go on the appropriate forum (stackoverflow or gradle's community forums).
