### ISSUE TITLE
GitHub Action Alternative

### ISSUE THREAD

**Issue by JLLeitschuh** [ZacSweers/check-gradle-checksums#2]
I just want to give you a heads up that we just rolled out a GitHub action to do this same check as well.

https://github.com/gradle/wrapper-validation-action

**Comment by ZacSweers** [comment]
Yup thanks! I'll leave this up for non-actions solutions

**Comment by JLLeitschuh** [comment]
You want to add a mention of it from the README?

**Comment by ZacSweers** [comment]
PR welcome!
